# Generated by Django 4.1.5 on 2023-02-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_alter_aboutme_options_alter_albom_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-pk'], 'verbose_name': 'Фотографию', 'verbose_name_plural': 'Фотографии'},
        ),
        migrations.AddField(
            model_name='blog',
            name='price',
            field=models.ImageField(default=1000, upload_to='', verbose_name='Стоимость'),
        ),
    ]
