# Generated by Django 4.1.5 on 2023-02-16 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0005_alter_photo_options_blog_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='price',
            field=models.IntegerField(default=1000, verbose_name='Стоимость'),
        ),
    ]
